# Generated by Django 5.1.4 on 2025-01-13 16:06

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('ref_user', models.CharField(max_length=255)),
                ('Supplier_name', models.CharField(max_length=255)),
                ('Supplier_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Supplier_address', models.TextField(blank=True, null=True)),
                ('Supplier_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_items', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('last_update_date', models.DateField(auto_now=True)),
                ('last_update_time', models.TimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
