# Generated by Django 5.1.4 on 2025-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0002_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name='Party Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('totalExpence', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
