# Generated by Django 5.1.4 on 2025-01-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0003_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('batch', models.CharField(max_length=100, verbose_name='Batch')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chemiboostapp.purchase')),
            ],
        ),
    ]
