# Generated by Django 5.1.4 on 2025-01-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0004_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='party',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='chemiboostapp.party'),
        ),
    ]
