# Generated by Django 5.1.4 on 2025-01-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0008_alter_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='user_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='chemiboostapp.userdetails'),
            preserve_default=False,
        ),
    ]
