# Generated by Django 5.1.4 on 2025-01-17 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0009_party_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='id',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='PurchaseItemID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='companylatitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='companylongitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 16, 23, 6, 14, 200111), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
