# Generated by Django 5.1.4 on 2025-01-17 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0010_remove_purchaseitem_id_purchaseitem_purchaseitemid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 16, 23, 6, 41, 581595), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
