# Generated by Django 5.1.4 on 2025-01-18 15:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0011_alter_userdetails_next_subscription_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='chemiboostapp.party'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 17, 21, 19, 3, 980100), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
