# Generated by Django 5.1.4 on 2025-01-24 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0014_purchase_totalgstamount_purchaseitem_totalgstamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='ref_user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 23, 22, 51, 40, 25821), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
