# Generated by Django 5.1.4 on 2025-01-29 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0015_purchaseitem_ref_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('PurchaseItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ref_user', models.CharField(default='', max_length=255)),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('batch', models.CharField(max_length=100, verbose_name='Batch')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate')),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cgst In persentage')),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sgst In persentage')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('totalGSTamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total GST amount')),
                ('totalWithGST', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total with GST')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 28, 21, 10, 56, 222962), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
