# Generated by Django 5.1.4 on 2025-02-02 06:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0016_medicinestock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('ref_user', models.CharField(default='', max_length=255)),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Customer Contact')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Customer Address')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount')),
                ('total_GST', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total GST Amount')),
                ('total_with_GST', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount with GST')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Amount')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=50, verbose_name='Payment Method')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='Pending', max_length=50, verbose_name='Payment Status')),
                ('billing_date', models.DateField(auto_now_add=True, verbose_name='Billing Date')),
                ('billing_time', models.TimeField(auto_now_add=True, verbose_name='Billing Time')),
                ('last_update_date', models.DateField(auto_now=True, verbose_name='Last Update Date')),
                ('last_update_time', models.TimeField(auto_now=True, verbose_name='Last Update Time')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_user', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 3, 4, 12, 8, 59, 197430), verbose_name='Next Subscription Expiry Date'),
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('billingItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ref_user', models.CharField(default='', max_length=255)),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('batch', models.CharField(max_length=100, verbose_name='Batch')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate per Unit')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount')),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='CGST %')),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='SGST %')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('total_GST_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total GST Amount')),
                ('total_with_GST', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total with GST')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chemiboostapp.billing')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='chemiboostapp.customer'),
        ),
    ]
