# Generated by Django 5.1.4 on 2025-03-14 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0018_billing_total_profit_billingitem_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='Dis',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='Free',
            field=models.IntegerField(default=0, verbose_name='Free Medicine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 4, 13, 20, 16, 42, 182628), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
