# Generated by Django 5.1.4 on 2025-03-15 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0019_purchaseitem_dis_purchaseitem_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestock',
            name='UnitPack',
            field=models.CharField(default='', max_length=16, verbose_name='UnitPack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='UnitPack',
            field=models.CharField(default=0, max_length=16, verbose_name='UnitPack'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 16, 51, 58, 586502), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
