# Generated by Django 5.1.4 on 2025-03-16 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0020_medicinestock_unitpack_purchaseitem_unitpack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='DL_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='party',
            name='contact_number2',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 22, 55, 27, 889475), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
