# Generated by Django 5.1.4 on 2025-03-18 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemiboostapp', '0021_party_dl_number_party_contact_number2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Offer',
            field=models.CharField(default='', max_length=15, verbose_name='Offer Applied'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='Offer',
            field=models.CharField(default='', max_length=15, verbose_name='Next Offer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='DL_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='party',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='next_subscription_expiry',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 13, 25, 28, 87776), verbose_name='Next Subscription Expiry Date'),
        ),
    ]
